USE db_bookstore;

-- Seed roles needed by Spring Security mapping (ROLE_ prefix is added in code).
INSERT INTO `role` (`role_name`, `description`)
SELECT 'ADMIN', 'Quan tri he thong'
WHERE NOT EXISTS (
    SELECT 1 FROM `role` WHERE UPPER(`role_name`) = 'ADMIN'
);

INSERT INTO `role` (`role_name`, `description`)
SELECT 'USER', 'Nguoi dung thong thuong'
WHERE NOT EXISTS (
    SELECT 1 FROM `role` WHERE UPPER(`role_name`) = 'USER'
);

-- Credentials for Postman quick-start:
-- admin / Admin@123
-- user  / User@123
-- BCrypt hashes are generated by Spring BCryptPasswordEncoder.
INSERT INTO `user` (
    `role_id`, `username`, `password`, `email`, `phone`, `address`, `full_name`, `total_points`, `status`, `version`
)
VALUES (
    (SELECT `role_id` FROM `role` WHERE UPPER(`role_name`) = 'ADMIN' LIMIT 1),
    'admin',
    '$2a$10$HZf/MUm2ZAKSOTuMLHYYD.pl2kn2qaNBtheCNXGLAuK1UWCebqcx.',
    'admin@bookstore.local',
    '0900000001',
    'Ha Noi',
    'Tai khoan Admin',
    0,
    1,
    0
)
ON DUPLICATE KEY UPDATE
    `role_id` = VALUES(`role_id`),
    `password` = VALUES(`password`),
    `email` = VALUES(`email`),
    `phone` = VALUES(`phone`),
    `address` = VALUES(`address`),
    `full_name` = VALUES(`full_name`),
    `status` = VALUES(`status`),
    `updated_at` = CURRENT_TIMESTAMP;

INSERT INTO `user` (
    `role_id`, `username`, `password`, `email`, `phone`, `address`, `full_name`, `total_points`, `status`, `version`
)
VALUES (
    (SELECT `role_id` FROM `role` WHERE UPPER(`role_name`) = 'USER' LIMIT 1),
    'user',
    '$2a$10$QihcRi6.jAnX11gVEbXEx.pyoNBPvD6QrULyYCeY14PYu1QS04NNC',
    'user@bookstore.local',
    '0900000002',
    'Ha Noi',
    'Tai khoan User',
    0,
    1,
    0
)
ON DUPLICATE KEY UPDATE
    `role_id` = VALUES(`role_id`),
    `password` = VALUES(`password`),
    `email` = VALUES(`email`),
    `phone` = VALUES(`phone`),
    `address` = VALUES(`address`),
    `full_name` = VALUES(`full_name`),
    `status` = VALUES(`status`),
    `updated_at` = CURRENT_TIMESTAMP;

